name: postres_app
description: "Enamorado de mi princesa."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  path_provider: ^2.0.15
  intl: ^0.20.2
  sqflite: ^2.3.0
  path: ^1.9.0
  flutter_typeahead: ^5.2.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  firebase_core: ^3.1.1 
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  connectivity_plus: ^6.0.3
  workmanager: ^0.6.0
  archive: ^4.0.7
  fl_chart: ^0.68.0
  vector_math: ^2.1.4
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  http: ^1.2.0
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/